# Generated by Django 3.0.2 on 2020-01-25 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200124_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(choices=[('EXTRASMALL', 'Extra Small'), ('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large'), ('EXTRALARGE', 'Extra Large')], default='MEDIUM', max_length=10),
            preserve_default=False,
        ),
    ]
