# Generated by Django 3.0.2 on 2020-01-28 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200122_0004'),
        ('orders', '0009_cartitem_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('size', models.CharField(choices=[('EXTRASMALL', 'Extra Small'), ('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large'), ('EXTRALARGE', 'Extra Large')], max_length=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderitems', to='products.Product')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.Order')),
            ],
        ),
    ]
