# Generated by Django 3.0.2 on 2020-01-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_cart_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_charge_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
