# Generated by Django 3.0.2 on 2020-01-17 02:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tag', models.CharField(blank=True, choices=[('SALE', 'Sale'), ('NEW', 'New'), ('HOT', 'Hot'), ('LOW', 'Low Stock!'), ('OUT', 'Out of stock.')], max_length=4)),
                ('type', models.CharField(blank=True, choices=[('SHIRT', 'Shirt'), ('PANTS', 'Pants'), ('OUTERWEAR', 'OuterWear')], max_length=9)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.Product')),
            ],
        ),
    ]
