# Generated by Django 3.0.2 on 2020-01-21 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='img',
            new_name='image',
        ),
    ]
