# Generated by Django 3.0.2 on 2020-01-29 23:11

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200122_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=stdimage.models.StdImageField(upload_to='images/'),
        ),
    ]
