# Generated by Django 3.0.2 on 2020-01-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='legs',
            field=models.IntegerField(default=2),
        ),
    ]
