# Generated by Django 3.0.2 on 2020-01-23 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_legs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='legs',
        ),
    ]
