# Generated by Django 3.0.2 on 2020-01-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200127_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='defaultAddress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip',
            field=models.CharField(max_length=10),
        ),
    ]
